[codestyle]
indent_type = 'space'
indent_width = 4
workspace_dir = '~/atcoder_practice'
lang = 'cpp'
template_file='~/atcoder_practice/template.cpp'
[etc]
download_without_login=false
parallel_download=false
save_no_session_cache=false